### ISSUE TITLE
Bug: Occasional RuntimeError during generation

### ISSUE THREAD

**Issue by MatthewMarinets** [Ziktofel/Archipelago#125]
### What happened?

Generation fails with a RuntimeError: Set changed size during iteration
```
Traceback (most recent call last):
  File "D:\Archipelago\matthew\Archipelago\Generate.py", line 642, in <module>
    multiworld = main()
  File "D:\Archipelago\matthew\Archipelago\Generate.py", line 228, in main
    return callback(erargs, seed)
  File "D:\Archipelago\matthew\Archipelago\Main.py", line 123, in main
    AutoWorld.call_all(world, "create_items")
  File "D:\Archipelago\matthew\Archipelago\worlds\AutoWorld.py", line 150, in call_all
    call_single(multiworld, method_name, player, *args)
  File "D:\Archipelago\matthew\Archipelago\worlds\AutoWorld.py", line 140, in call_single
    raise e
  File "D:\Archipelago\matthew\Archipelago\worlds\AutoWorld.py", line 133, in call_single
    ret = _timed_call(method, *args, multiworld=multiworld, player=player)
  File "D:\Archipelago\matthew\Archipelago\worlds\AutoWorld.py", line 119, in _timed_call
    ret = method(*args)
  File "D:\Archipelago\matthew\Archipelago\worlds\sc2\__init__.py", line 82, in create_items
    pool = get_item_pool(self.multiworld, self.player, self.mission_req_table, starter_items, excluded_items, self.location_cache)
  File "D:\Archipelago\matthew\Archipelago\worlds\sc2\__init__.py", line 346, in get_item_pool
    filtered_pool = filter_items(multiworld, player, mission_req_table, location_cache, pool, existing_items, locked_items)
  File "D:\Archipelago\matthew\Archipelago\worlds\sc2\PoolFilter.py", line 528, in filter_items
    valid_items = valid_inventory.generate_reduced_inventory(inventory_size, mission_requirements)
  File "D:\Archipelago\matthew\Archipelago\worlds\sc2\PoolFilter.py", line 434, in generate_reduced_inventory
    logical_inventory_set.difference_update((item_name for item_name in logical_inventory_set if item_name.endswith("(Archon)")))
  File "D:\Archipelago\matthew\Archipelago\worlds\sc2\PoolFilter.py", line 434, in <genexpr>
    logical_inventory_set.difference_update((item_name for item_name in logical_inventory_set if item_name.endswith("(Archon)")))
RuntimeError: Set changed size during iteration
```

This seems to happen when the correct code path is taken to land on line 434 of PoolFilter.py, and something gets removed. Said line:
```Python
logical_inventory_set.difference_update((item_name for item_name in logical_inventory_set if item_name.endswith("(Archon)")))
```
This is probably fixed by just replacing the brackets so the argument expression is fully evaluated up front before `logical_inventory_set` is modified:
```Python
logical_inventory_set.difference_update([item_name for item_name in logical_inventory_set if item_name.endswith("(Archon)")])
```
However, I haven't found a consistent way to reproduce this issue, and it seems rare.

### What were the expected results?

Generation does not crash.

### Software

Local generation

**Comment by Ziktofel** [comment]
I think that got fixed by test fixing
